package com.example.smartpantrymanager.data.repositories;

import android.content.ContentValues;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import com.example.smartpantrymanager.core.enums.UnitType;
import com.example.smartpantrymanager.data.connection.DBHelper;
import com.example.smartpantrymanager.domain.interfaces.IPantryIngredientRepository;
import com.example.smartpantrymanager.domain.models.PantryIngredient;

import java.util.ArrayList;

public class PantryIngredientRepository implements IPantryIngredientRepository {
    private DBHelper dbHelper;

    public PantryIngredientRepository(DBHelper dbHelper) {
        this.dbHelper = dbHelper;
    }

    // method used to get all pantry ingredients
    public ArrayList<PantryIngredient> getAllPantryIngredients(){

        ArrayList<PantryIngredient> pantryIngredients = new ArrayList<>();
        SQLiteDatabase db = dbHelper.getReadableDatabase();

        Cursor cursor = db.rawQuery(
                "SELECT PI_Id, Ingredient_Id, PI_Qty, PI_Unit " +
                        "FROM Pantry_Ingredient",
                null
        );

        if (cursor.moveToFirst()) {

            do {

                int piId =
                        cursor.getInt(cursor.getColumnIndexOrThrow("PI_Id"));
                int ingredientId =
                        cursor.getInt(cursor.getColumnIndexOrThrow("Ingredient_Id"));
                double piQty =
                        cursor.getDouble(cursor.getColumnIndexOrThrow("PI_Qty"));
                String piUnitString =
                        cursor.getString(cursor.getColumnIndexOrThrow("PI_Unit"));
                UnitType piUnit =
                        UnitType.valueOf(piUnitString);

                PantryIngredient pantryIngredient =
                        new PantryIngredient(
                                piId,
                                ingredientId,
                                piQty,
                                piUnit
                        );

                pantryIngredients.add(pantryIngredient); // adds the pantry ingr to the arraylist

            }

            while (cursor.moveToNext()); // moves to the next instance
        }

        cursor.close(); // closes the cursor

        return pantryIngredients; // returns an array list of pantry ingredients
    }

    // method used for adding a new pantry ingredient instance
    public void addPantryIngredient(PantryIngredient pantryIngredient){

        SQLiteDatabase db = dbHelper.getWritableDatabase();

        ContentValues values = new ContentValues();

        values.put("Ingredient_Id", pantryIngredient.getIngredientId());
        values.put("PI_Qty", pantryIngredient.getPantryIngredientQty());
        values.put(
                "PI_Unit",
                pantryIngredient.getPantryIngredientUnit().name()
        );

        long generatedId = db.insert(
                "Pantry_Ingredient",
                null,
                values
        );

        // this needed to be set since it's generated by the db
        pantryIngredient.setPantryIngredientId((int) generatedId);

    }

    // this method will be used to delete a specific ingredient
    public void deletePantryIngredient(PantryIngredient pantryIngredient) {

        SQLiteDatabase db = dbHelper.getWritableDatabase();

        db.delete(
                "Pantry_Ingredient",
                "PI_Id = ?",
                new String[]{
                        String.valueOf(pantryIngredient.getPantryIngredientId())
                }
        );
    }

    // this method will be used to update a specific pantry ingredient
    public void updatePantryIngredient(PantryIngredient pantryIngredient) {

        SQLiteDatabase db = dbHelper.getWritableDatabase();

        ContentValues values = new ContentValues();

        values.put("Ingredient_Id", pantryIngredient.getIngredientId());
        values.put("PI_Qty", pantryIngredient.getPantryIngredientQty());
        values.put("PI_Unit", pantryIngredient.getPantryIngredientUnit().name());

        db.update(
                "Pantry_Ingredient",
                values,
                "PI_Id = ?",
                new String[]{

                        String.valueOf(pantryIngredient.getPantryIngredientId())

                }
        );
    }
}
